addressbook/config/routes.rb
Addressbook::Application.routes.draw do
  resources :contacts

  

end

addressbook/app/models/contact.rb
class Contact < ActiveRecord::Base
end

addressbook/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

addressbook/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render action: 'show', status: :created, location: @contact }
      else
        format.html { render action: 'new' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :surname, :cell, :email, :address)
    end
end

addressbook/app/helpers/application_helper.rb
module ApplicationHelper
end

addressbook/app/helpers/contacts_helper.rb
module ContactsHelper
end

addressbook/app/views/contacts/_form.html.erb
<%= form_for @contact, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :surname, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :surname, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :cell, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :cell, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                contacts_path, :class => 'btn' %>
  </div>
<% end %>

addressbook/app/views/contacts/edit.html.erb
<%- model_class = Contact -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

addressbook/app/views/contacts/index.html.erb
<%- model_class = Contact -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:surname) %></th>
      <th><%= model_class.human_attribute_name(:cell) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= link_to contact.id, contact_path(contact) %></td>
        <td><%= contact.name %></td>
        <td><%= contact.surname %></td>
        <td><%= contact.cell %></td>
        <td><%= contact.email %></td>
        <td><%= contact.address %></td>
        <td><%=l contact.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_contact_path(contact), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      contact_path(contact),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_contact_path,
            :class => 'btn btn-primary' %>

addressbook/app/views/contacts/new.html.erb
<%- model_class = Contact -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

addressbook/app/views/contacts/show.html.erb
<%- model_class = Contact -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @contact.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:surname) %>:</strong></dt>
  <dd><%= @contact.surname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cell) %>:</strong></dt>
  <dd><%= @contact.cell %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @contact.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @contact.address %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              contacts_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_contact_path(@contact), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              contact_path(@contact),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

addressbook/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Addressbook" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Addressbook</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>